AWSTemplateFormatVersion: '2010-09-09'

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "UserTable"
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "UserIndex"
          KeySchema:
            - AttributeName: "SK"
              KeyType: "HASH"
            - AttributeName: "PK"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

  FundTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "FundTable"
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  TransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "TransactionTable"
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST