AWSTemplateFormatVersion: '2010-09-09'

Resources:
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "ClientNotifications"
      DisplayName: "Client Notifications"

  SnsPublishPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "SNSPublishPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sns:Publish"
            Resource: !Ref NotificationTopic
      Roles:
        - !Ref LambdaExecutionRole

Outputs:
  SnsTopicArn:
    Description: "The ARN of the SNS Topic for client notifications"
    Value: !Ref NotificationTopic
